Added HUD, coin icon
SamBumgardner/csc-303-platformer pull request #7
Opened 2017-04-12 21:27 UTC by Dwooll94

Created a statically accessed HUD and added a coin icon. All numeric fields are fixed width and will trim off the front of the number if too large for HUD.

2017-04-13 02:09 UTC, KeithCissell reviewed
The code is really clean and the output of the HUD looks really good, especially with the shadow styling. One thing you might look into next is how to make sure the HUD displays are above the map so the two don't overlap. I left a comment about possible redundant code and the update function. Another thing you might add would be a variable for a playClock. Then in the update function for the HUD, add logic that increments the timeClock every second and passes the new time to 'handleTimeUpdate'.

2017-04-13 02:09 UTC, KeithCissell commented on source/HeadsUpDisplay.hx
> +		timeString = timeString.substr(0, -parsedLength) + parsedTime;
I noticed that in this function and in 'handleCoinsUpdate' you have a line to set a their string values, but in the if statement following that you either set that string to that same value again or another format. Seems redundant, but there may have been a reason you needed to do it this way.

2017-04-13 02:16 UTC, KeithCissell commented on source/HeadsUpDisplay.hx
> +		coinString = coinString.substr(0, -parsedLength) + parsedCoins;
Other possible redundancy

2017-04-13 02:17 UTC, KeithCissell commented on source/HeadsUpDisplay.hx
> +
You need to call 'super.update(elapsed);' at the very end of this update function

2017-04-13 02:31 UTC, KeithCissell commented on source/HeadsUpDisplay.hx
> +		//UPDATES
I don't think each of these items need below need to have update called on them. You would just put logic here that updated them using the functions you created above. For example, you would check the time elapsed and if it had been a full second call 'handelTimeUpdate()' with the new time.

2017-04-17 16:46 UTC, SamBumgardner requested changes
The documentation looks pretty good, but there is a change I'd like to have before it gets merged in.

At the top of every function's documentation block, put a short description of what the function is supposed to accomplish. See the `Player.hx` file for examples!

2017-04-17 20:51 UTC, SamBumgardner approved these changes

2017-04-17 20:55 UTC, merged